service: test

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-vpc-plugin
  - serverless-dependson-plugin

package:
  exclude:
  - .git/**
  - .vscode/**
  - .env.development

custom:
  serverless-offline:
    host: 0.0.0.0
    dontPrintOutput: true
  vpcConfig:
    cidrBlock: 10.0.0.0/16
    createNatGateway: true
    zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    subnetGroups:
      - rds
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  timeout: 30
  region: us-east-1
  logRetentionInDays: 30
  vpc:
    securityGroupIds:
      - Ref: LambdaExecutionSecurityGroup
    subnetIds:
      - Ref: AppSubnet1
      - Ref: AppSubnet2
      - Ref: AppSubnet3

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: POST
          cors: true
